Create Basic Settings Widget And New Download Dialog Basic UI
L-Super/FlowD pull request #3
Opened 2024-08-26 12:07 UTC by ProgramCX

-  Create SettingsBasicWidget basic ui
- Add switching-tabs-effects in SettingsWidget
- Create NewDownloadDialog basic ui
- Add some qss code for QWidget and QPlainTextEdit

2024-08-26 22:28 UTC, L-Super requested changes

2024-08-26 22:28 UTC, L-Super commented on src/main.cpp
> +    a.setWindowIcon(QIcon(":/resources/logo.png"));
这里为何换成png

2024-08-26 22:28 UTC, L-Super commented on src/MainWindow.cpp
> +        auto newDownloadDialog=new NewDownloadDialog;
未格式化

2024-08-27 03:22 UTC, ProgramCX commented on src/main.cpp
> +    a.setWindowIcon(QIcon(":/resources/logo.png"));
换png是因为我发现png转svg渐变部分处理的不是太好。那我用一下预定义，Windows直接用ico，macOS用icns。

2024-08-27 03:23 UTC, ProgramCX commented on src/MainWindow.cpp
> +        auto newDownloadDialog=new NewDownloadDialog;
> 未格式化

好的。

2024-08-27 06:26 UTC, merged